### ISSUE TITLE
Why does the container have google-cloud-sdk in it?

### ISSUE THREAD

**Issue by intendo** [ncbi/docker#23]
I can't see why the google-cloud-sdk is in the container.
It is over half the size of the image. 
The google-cloud-sdk is over 880 Megabytes.

**Comment by azat-badretdin** [comment]
Thank you for your report, Darren! Would you mind illustrating that? Thanks!

**Comment by intendo** [comment]
Add the following to the main Dockerfile to remove 880 Megabytes of disk space:
```RUN rm -rf /usr/share/google-cloud-sdk /usr/lib/google-cloud-sdk```

**Comment by azat-badretdin** [comment]
Thank you, Darren. 

We will investigate why do we have this in our image.

**Comment by christiam** [comment]
> I can't see why the google-cloud-sdk is in the container.

`gsutil` is needed in when downloading BLAST databases from GCP whenever Requester Pays is enabled on a bucket. 
In BLAST+ 2.16.0 we have made efforts to reduce the size of the `ncbi/blast` docker image; this led to about a 50% reduction in size: https://hub.docker.com/r/ncbi/blast/tags

> The google-cloud-sdk is over 880 Megabytes.

This is a known issue: https://github.com/GoogleCloudPlatform/gsutil/issues/1732
