### ISSUE TITLE
Docker hub image (ncbi/blast/2.13.0) has signature-related error

### ISSUE THREAD

**Issue by pragermh** [ncbi/docker#26]
Hi,
I've been using your image in my flask app for a while now, so thanks for making that possible! When I try to build from your [ncbi/blast/2.13.0](https://hub.docker.com/layers/ncbi/blast/2.13.0/images/sha256-ae7aaf7dbb861d8c2e4c59738101d98548ea5578cd412bffa0b24a6aca8ceced?context=explore) image on docker hub, however, I suddenly get:
`GPG error: https://packages.cloud.google.com/apt cloud-sdk-buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05`
whereas the same thing worked when my colleague built from this repo instead, so perhaps you need to update the docker hub image?
/ M

**Comment by christiam** [comment]
Hi, I'm sorry for the late reply. Does this issue still occur with the most recent version of the docker image https://hub.docker.com/r/ncbi/blast/tags ?

**Comment by pragermh** [comment]
No 🙂.

**Comment by pragermh** [comment]
Hi, It seems I get the same issue with 2.14 & 2.15 now:
`GPG error: https://packages.cloud.google.com/apt cloud-sdk-bullseye InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C0BA5CE6DC6315A3`
