### ISSUE TITLE
No docker.io/ncbi/blast-static:2.15.0 images

### ISSUE THREAD

**Issue by nathanweeks** [ncbi/docker#47]
docker.io/ncbi/blast-static:2.15.0 images haven't been built yet:
https://hub.docker.com/r/ncbi/blast-static/tags

**Comment by christiam** [comment]
@nathanweeks , can you use the 2.15.0 docker image in https://hub.docker.com/r/ncbi/blast/tags ?

**Comment by nathanweeks** [comment]
For the most part yes, though I've encountered at least a couple limitations:

1. No linux/arm64/v8 builds, which can present problems with (at least) local development/use on macOS
2. (Minor issue) the uncompressed image size of docker.io/ncbi/blast:2.15.0 is almost 2X larger docker/ncbi/blast-static:2.15.0 (~1.69 GB vs. ~858 MB), even though the dynamically-linked version should in principle be much smaller, primarily due to https://github.com/ncbi/docker/issues/23 (and to a lesser extent due to the retention of source code & build artifacts in image layers). Also more CVEs to get flagged by container security scanners.

Is a linux/arm64 build of ncbi/blast planned?

**Comment by christiam** [comment]
Yes, we'll update the docker images in the next month. I'm sorry for the inconvenience.

**Comment by christiam** [comment]
@nathanweeks , the docker.io/ncbi/blast-static:2.15.0 image has been updated.
